### ISSUE TITLE
Compiler warning regarding table relationship

### ISSUE THREAD

**Issue by srseibs** [MatthiasKerat/OrderApplikationYT#2]
Hi Matthias - There is an ominous sounding warning in the build log (try Build -> Rebuild Project). SQL is tricky enough (for me) with table joins, etc., but Room makes this very hard to understand.

> Task :app:kaptDebugKotlin
C:\Users\Mike\Documents\Android\AndroidStudioProjects\YouTubeClasses\K Apps\OrderSystem\app\build\tmp\kapt3\stubs\debug\com\sailinghawklabs\
ordersystem\core\data\local\entity\OrderedProductEntity.java:11: 

warning: The column productId in the junction entity com.sailinghawklabs.ordersystem.core.data.local.entity.OrderedProductEntity is being used to resolve a relationship but it is not covered by any index. This might cause a full table scan when resolving the relationship, it is highly advised to create an index that covers this column.
    private final java.lang.String productId = null;

**Comment by MatthiasKerat** [comment]
Hello. Yes this is indeed a warning which should not be ignored. Especially if there are a lot of table entries. We can solve this in OrderProductEntity with the following annotation for productId -> @ColumnInfo(index = true). Its very well explained here: https://stackoverflow.com/questions/71538169/this-might-cause-a-full-table-scan-when-resolving-the-relationship-it-is-highly
